version: '3.3'

services:
  # Stage 1: Build
  app-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-builder
    working_dir: /usr/src/app

  # Stage 2: Run
  app-runner:
    image: nginxinc/nginx-unprivileged
    container_name: app-runner
    ports:
      - "8080:80"  # Adjust the port as needed
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - app-builder
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
